import { useEffect, useState } from "react";
import { Alert, Badge, Button, Card, Col, Form, Row, Spinner } from "react-bootstrap";
import { Link, useParams } from "react-router-dom";
import { abortWorkout, completeWorkout, getWorkout, logSet, startWorkout } from "../services/workoutEngineService";
import type { WorkoutDto } from "../types/workouts";

export function WorkoutExecutionPage() {
  const { workoutId } = useParams<{ workoutId: string }>();
  const [workout, setWorkout] = useState<WorkoutDto | null>(null);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState<string | null>(null);
  const [values, setValues] = useState<Record<string, Record<string, string>>>({});
  const load = () => { if (workoutId) getWorkout(workoutId).then(setWorkout).catch(() => setError("Não foi possível carregar o treino.")); };
  useEffect(() => { load(); }, [workoutId]); // eslint-disable-line react-hooks/exhaustive-deps
  if (!workout) return error ? <Alert variant="danger" className="mt-4">{error}</Alert> : <Spinner animation="border" className="mt-4" aria-label="Carregando treino" />;
  const setValue = (key: string, field: string, value: string) => setValues((current) => ({ ...current, [key]: { ...current[key], [field]: value } }));
  const execute = async (action: "start" | "complete" | "abort") => { try { const next = action === "start" ? await startWorkout(workout.id) : action === "complete" ? await completeWorkout(workout.id) : await abortWorkout(workout.id); setWorkout(next); } catch { setError("Não foi possível atualizar o estado do treino."); } };
  const saveSet = async (exerciseId: string, index: number) => { const key = `${exerciseId}-${index}`; setSaving(key); try { await logSet(exerciseId, index, { actual_reps: Number(values[key]?.reps) || null, actual_load: values[key]?.load || null, rpe: values[key]?.rpe ? Number(values[key].rpe) : null }); load(); } catch { setError("Não foi possível registrar a série."); } finally { setSaving(null); } };
  return <div className="py-4"><div className="d-flex justify-content-between align-items-start mb-4"><div><Link to="/workouts">← Histórico</Link><h1 className="mt-2">{workout.name}</h1><Badge bg={workout.status === "completed" ? "success" : workout.status === "in_progress" ? "info" : workout.status === "aborted" ? "danger" : "secondary"}>{workout.status}</Badge></div><div>{workout.status === "planned" && <Button onClick={() => void execute("start")}>Iniciar treino</Button>}{workout.status === "in_progress" && <><Button variant="success" className="me-2" onClick={() => void execute("complete")}>Finalizar treino</Button><Button variant="outline-danger" onClick={() => void execute("abort")}>Abortar</Button></>}</div></div>{error && <Alert variant="danger">{error}</Alert>}{workout.exercises?.map((exercise) => <Card className="mb-3" key={exercise.id}><Card.Body><Card.Title>{exercise.sequence_index + 1}. {exercise.exercise_name || "Exercício"}</Card.Title><p className="text-muted">Planejado: {exercise.planned_sets} séries{exercise.planned_reps ? ` × ${exercise.planned_reps} reps` : ""}{exercise.planned_load ? ` · ${exercise.planned_load}` : ""}</p>{Array.from({ length: exercise.planned_sets }, (_, index) => { const key = `${exercise.id}-${index}`; const logged = exercise.set_logs.some((item) => item.set_index === index); return <Row className="align-items-end g-2 mb-2" key={key}><Col xs={2}><strong>Série {index + 1}</strong></Col><Col><Form.Label className="visually-hidden">Repetições</Form.Label><Form.Control aria-label={`Repetições série ${index + 1}`} placeholder="Reps" type="number" min="0" value={values[key]?.reps || ""} onChange={(event) => setValue(key, "reps", event.target.value)} /></Col><Col><Form.Label className="visually-hidden">Carga</Form.Label><Form.Control aria-label={`Carga série ${index + 1}`} placeholder="Carga" value={values[key]?.load || ""} onChange={(event) => setValue(key, "load", event.target.value)} /></Col><Col><Form.Label className="visually-hidden">RPE</Form.Label><Form.Control aria-label={`RPE série ${index + 1}`} placeholder="RPE" type="number" min="1" max="10" value={values[key]?.rpe || ""} onChange={(event) => setValue(key, "rpe", event.target.value)} /></Col><Col xs="auto">{logged ? <Badge bg="success">Registrada</Badge> : <Button size="sm" disabled={workout.status !== "in_progress" || saving === key} onClick={() => void saveSet(exercise.id, index)}>{saving === key ? "Salvando…" : "Concluir série"}</Button>}</Col></Row>; })}</Card.Body></Card>)}{(!workout.exercises || workout.exercises.length === 0) && <Alert variant="info">Este treino ainda não possui exercícios. Adicione exercícios pelo catálogo antes de iniciar.</Alert>}</div>;
}

export default WorkoutExecutionPage;